### ISSUE TITLE
Please add CJUHSD.net

### ISSUE THREAD

**Issue by MDMoya** [GSA/govt-urls#135]
Please add the Chaffey Joint Union High School District (cjuhsd.net) district, a California Public High School only district, to the list so we can leverage TAK in our emergency response plan.

**Comment by dawnpm** [comment]
Hello, Apologies, K-12 is out of scope for this list - see https://search.gov/about/policy/govt-urls.html. Any questions should be directed to TAK, we don't have direct involvement in their service.
