### ISSUE TITLE
Add DOD URL

### ISSUE THREAD

**Issue by afeijoo** [GSA/govt-urls#26]
http://www.cultureready.org/ from the Defense Language and National Security Education Office

**Comment by dawnpm** [comment]
Submitted by Marc Hill via helpdesk email August 19, 2020:

"www.CultureReady.org. The DoD Culture Team is part of the Defense Language and National Security Office which falls under DHRA at the Mark Center. Our website contains resources for culture education and training for use by DoD members as well as other stakeholders including study abroad students."

**Comment by h-m-f-t** [comment]
Oh, cultureready.org is already on list (#76), but dlnseo.org isn't. We'll add that one.
