### ISSUE TITLE
rewardsforjustice.net

### ISSUE THREAD

**Issue by h-m-f-t** [GSA/govt-urls#29]
**Domain**: [rewardsforjustice.net](https://rewardsforjustice.net)
**Managing agency**: Department of State
**Location (State), if applicable**: Washington, DC (probably 🤷‍♂️)
**Any notes about the purpose or scope of the site**: 
* https://www.state.gov/rewards-for-justice-reward-offer-for-information-on-foreign-interference-in-u-s-elections/
* https://www.theverge.com/2020/8/5/21356325/us-10-million-reward-foreign-election-interference-hacker
* https://www.zdnet.com/article/us-offers-10-million-reward-for-hackers-meddling-in-us-elections/

**Comment by dawnpm** [comment]
Thanks @h-m-f-t , will check it out

**Comment by h-m-f-t** [comment]
Check out rfj.tips, too.

**Comment by h-m-f-t** [comment]
Added in #78
