### ISSUE TITLE
Updates to Oregon city and county websites

### ISSUE THREAD

**Issue by RadleyMadish** [GSA/govt-urls#35]
Some of the URLs listed were inacccurate

Sherman County, OR is listed with sherman-county.com, which redirects to what looks like a hotel website. The correct address is co.sherman.or.us

Canby, OR (listed as ci.canby.or.us), Phoenix, OR (phoenixoregon.net), Springfield, OR (ci.springfield.or.us), and Happy Valley, OR (ci.happy-valley.or.us) all now use .gov websites, and the URLs listed here are all broken or lead to 404 pages.

**Comment by dawnpm** [comment]
Thank you for your submission, @RadleyMadish , much appreciated. If there are any other updates you know of, please let us know.

**Comment by RadleyMadish** [comment]
One more, Clark County, WA now uses a .gov website, so the website listed for it, co.clark.wa.us, no longer works.

**Comment by dawnpm** [comment]
Thanks again.
