### ISSUE TITLE
Oregon Indian Tribe websites

### ISSUE THREAD

**Issue by RadleyMadish** [GSA/govt-urls#36]
There are some Indian Tribes in Oregon that aren't currently listed

Coquille Indian Tribe - www.coquilletribe.org
Confederated Tribes of Grand Ronde - www.grandronde.org
Confederated Tribes of Siletz Indians - www.ctsi.nsn.us
Confederated Tribes of the Umatilla Indian Reservation - ctuir.org
Confederated Tribes of Warm Springs - www.warmsprings.com (though this redirects to their current .gov website, so I don't know if that counts for this list)
Cow Creek Band of Umpqua Tribe of Indians - cowcreek.com (same deal, redirects to their current .gov website)
Klamath Tribes - klamathtribes.org

There's also the Columbia River Inter-Tribal Fish Commission, which is the fishery coordinating agency of four Columbia River treaty tribes, at www.critfc.org, but I'm not sure if that counts as governmental enough.

**Comment by dawnpm** [comment]
Thanks for your submissions, @RadleyMadish !
