### ISSUE TITLE
The U.S. Army Band - DoD

### ISSUE THREAD

**Issue by TUSAB-web** [GSA/govt-urls#37]
Please add usarmyband.com to the list. Our site has been around for many years, but for some reason it doesn’t appear to be on this list. The U.S. Army Band is a military unit, part of the U.S. Army Military District of Washington.

"The United States Army Band "Pershing's Own" provides musical support for the leadership of the United States, to include all branches of government, and to a wide spectrum of national and international events in order to connect the Army to the American people."

**Comment by h-m-f-t** [comment]
https://www.usarmyband.com/important-information says:

> Such links are provided consistent with the stated purpose of this DoD Web site.

> This government computer system uses software programs to create summary statistics...

> Disclosure of any information by you is strictly voluntary. Information is being submitted to and stored securely on a DOD-owned website. 

Matthew Smith, webmaster, is also listed in WHOIS for the domain.

**Comment by TUSAB-web** [comment]
Thank you!
