### ISSUE TITLE
OPM domains not on .gov

### ISSUE THREAD

**Issue by h-m-f-t** [GSA/govt-urls#44]
I have it firsthand that the following domains are registered and managed by OPM, mostly as parked domains:

* usajobs.com
* cfcgiving.org
* combinedfederal.org
* federalcampaign.org
* usajobsrecruit.com
* usajobsrecruit.us
* usajobsassess.com
* usajobsassess.us

**Comment by dawnpm** [comment]
usajobs.com, usajobsrecruit.com, usajobsrecruit.us, usajobsassess.com, usajobsassess.us verified
other three pending further info.
