### ISSUE TITLE
Please add GASDF.US

### ISSUE THREAD

**Issue by dawnpm** [GSA/govt-urls#47]
Received through helpdesk - ZD 26240, SN INC3655134

[CARSON, C. D. CW2 MIL SDF GA (US)]
Wednesday ‪07:44 pm‬
 
Greetings,

Please add the domain: *gasdf.us <http://gasdf.us/> *to the existing govt
state listings.

This is an additional domain to the already established *gasdf.com
<[http://gasdf.com>.*](http://gasdf.com%3E.%2A/)
https://github.com/GSA/govt-urls/blob/master/3_govt_urls_state_only.csv

You can see that this email address domain is active.
https://directory.doas.ga.gov/Employee/Details/4740

If you have any questions please let me know. My contact info is below.

Best Regards,
CW2 Christopher Carson
1BDE HQ S3 - Communications Technical Officer
Georgia State Defense Force
706-506-5031
[christopher.carson@gasdf.us](mailto:christopher.carson@gasdf.us)

Classification: UNCLASSIFIED
Caveats: NONE

**Comment by sonofcar101** [comment]
Please let me know of any next steps required on my behalf.

**Comment by dawnpm** [comment]
gasdf.com, already on list - Registrant: Association of the Georgia State Defense Force, Inc.
gasdf.us, current request - Association of the Georgia State Defense Force

Also found:
paonews.net, gasdf.com website is mirrored on paonews.net, and menu links on gasdf.com go to paonews.net. https://ga.ng.mil/Leadership/Georgia-State-Defense-Force/ links to the paonews.net domain.
www.gasdf.org - beta site, refs join@gasdf.us
