### ISSUE TITLE
Please Add Domain

### ISSUE THREAD

**Issue by dawnpm** [GSA/govt-urls#50]
Ref: Incident INC3674843

Please add to local government list - ballardsvillefire.com. This is a 
local fire department supporting the Oldham County Task Force, Kentucky for 
SAR, HAZMAT, Drone Response, and Tech Rescue.

**Comment by Ratfire** [comment]
@dawnpm Hey! How long does it usually take to have a domain added?  Hoping for the elevated access in order to see and use the ArcGIS Plugin in TAK.  Thanks - Kenny

**Comment by h-m-f-t** [comment]
Hi @Ratfire. Can you share anything that outlines a requirement to be on this list in order to use ArcGIS Plugin in TAK? If you can't share it here, can you email it to me at cameron.dixon@cisa.dhs.gov?

**Comment by dawnpm** [comment]
related orgs on https://www.ballardsvillefire.com/content/links/
