### ISSUE TITLE
OMB Memo M-22-09 Action Item - Submission of SI Non-.Gov Domains

### ISSUE THREAD

**Issue by dawnpm** [GSA/govt-urls#53]
Ref: INC3684853

Hello GSA,

Please find attached a list of SI non-.gov domains.  This submission is in response to OMB Memo M-22-09, Moving the U.S. Government Toward Zero Trust Cybersecurity Principles, requiring agencies to provide any non-.gov hostnames they use to CISA and GSA.

The submission is provided using the instructions provided on https://github.com/GSA/govt-urls.

Please let me know if you have any questions regarding the submission.

Jason Tam

SOC Team Lead
Smithsonian Institution, OCIO
Office: (202) 633-0531

[SI Zero Trust Non-.Gov Domains.csv](https://github.com/GSA/govt-urls/files/8287055/SI.Zero.Trust.Non-.Gov.Domains.csv)

**Comment by dawnpm** [comment]
Unique second level:
cicadamerch.com
ellajenkins.com
nmaahcstore.com
searchablemuseum.com
seecstories.com
smithsonian.com
smithsonianearthtv.com
smithsonianstudentadventures.com
si.edu
artcollectorsprogram.org
discoverytheater.org
ecosystemsontheedge.org
mughalgardens.org
museumonmainstreet.org
paleoglot.org
smithsonianapa.org
smithsonianchambermusic.org
smithsoniancraft2wear.org
smithsoniancraftshow.org

Subdomains of domains already on list will not be added, e.g., *.si.edu.
Folders within domains already on list will not be added.
Kickstarter out of scope.

review WIP

**Comment by h-m-f-t** [comment]
These look good – several even have public contacts in Whois for SI.
