### ISSUE TITLE
GSA non-.gov domain list

### ISSUE THREAD

**Issue by aquintananieves** [GSA/govt-urls#57]
In accordance with M-22-09, Moving the U.S. Government Toward Zero Trust Cybersecurity Principles, Section III, Applications and Workloads, Action 5. Attached is the list non-.gov hostnames used by GSA.

- portal.glab-2.gsarba.com
- portal.fas.gsarba.com
- api.65345987.com
- wfm.cccfed.com
- portal.glab-3.gsarba.com
- portal.glab-4.gsarba.com
- gsa.ncmms.com
- fedroom.com

**Comment by h-m-f-t** [comment]
In an email on 5/9 to dotgov@cisa.dhs.gov, GSA confirmed that their vendor maintained the registrations for gsarba.com, 65345987.com, cccfed.com, ncmms.com, and fedroom.com.
