### ISSUE TITLE
DOL non-.gov Domain Reporting

### ISSUE THREAD

**Issue by dawnpm** [GSA/govt-urls#58]
Ref: INC3696716

Good Afternoon,

DOL SOC would like to bulk add/update some non-.gov domains to the master list to ensure we are compliant with OMB M-22-09 and the Federal Zero Trust Strategy. Please see attached and please let me know if you have any questions or concerns.

Thank you,
Emery R. Dussold

[non-gov-submission-template.csv](https://github.com/GSA/govt-urls/files/8445461/non-gov-submission-template.csv)

**Comment by dawnpm** [comment]
Ref ZD337

Good Afternoon,

DOL would like to make a few changes to our non-.gov submission list found in the repo https://github.com/GSA/govt-urls under issue #58.

DOL would like to remove:

app1.erg.com- DOL no longer manages, funds, or sponsors the site.
dol-appeals-sso.entellitrak.com- DOL vendor does not authorize testing.
workeronline.force.com- DOL no longer manages, funds, or sponsors the site.
vcn.org- DOL no longer manages, funds, or sponsors the site.

DOL would like to add:



Non-.gov Domain | Agency | Maintaining office | Use case | Type of government | Federal branch | State | Comments
-- | -- | -- | -- | -- | -- | -- | --
capeyouth.org | DOL | ODEP | Website | Federal | Executive | N/A | ODEP sponsored technical assistance center/initiative-Open To Public
inclusiveapprenticeship.org | DOL | ODEP | Website | Federal | Executive | N/A | ODEP sponsored technical assistance center/initiative-Open To Public
peatworks.org | DOL | ODEP | Website | Federal | Executive | N/A | ODEP sponsored technical assistance center/initiative-Open To Public

**Comment by h-m-f-t** [comment]
Added in #78
