### ISSUE TITLE
Request to Add sdl.usu.edu and usurf.sdl.usu Domains to the GSA Tables

### ISSUE THREAD

**Issue by dawnpm** [GSA/govt-urls#60]
Ref INC3720390

Hi,

In order to access the TAK.gov development tools and resources, we (The
Space Dynamics Laboratory) need to have our domains added to the GSA
tables. We've been told that this can be done by submitting an email to
this address with the following information:

Domain(s)

	sdl.usu.edu
	usurf.usu.edu

Federal agency responsible for the website, if applicable
	Missile Defense Agency (The Space Dynamics Laboratory's University Affiliated Research Center (UARC) sponsor)

Level of Government (Federal, State, Regional, County, Local, Native Sovereign Nation, or Quasigovernmental)
	Federal

Location (State), if applicable
	Utah

A note about the purpose or scope of the website
	Information pertaining to the Space Dynamics Laboratory, a University Affiliated Research Center (UARC)

Please let me know if you need any more information to process this
request.

Respectfully,

Daniel Hornberger 

Software Engineer 

Space Dynamics Laboratory 

Dawn has contact info if needed

**Comment by lightningWhite** [comment]
@dawnpm Good morning, how long does it typically take for domains to be added to the list? Our team is anxious to begin development as soon as this is complete and we have the access we need to TAK.gov's resources, and we're just wondering what kind of time frame we're dealing with.

**Comment by lightningWhite** [comment]
@h-m-f-t @dawnpm Good morning, I just wanted to check to see if there were any more updates on the progress of this issue, and if there is anything we could do to help it move to completion?

**Comment by dawnpm** [comment]
@lightningWhite just confirming that USU is out of scope, please see What's Not Included on https://search.gov/about/policy/govt-urls.html. If you have questions, please direct them to TAK, we do not have a relationship with them.
