### ISSUE TITLE
Additional HHS Domains

### ISSUE THREAD

**Issue by shalllbetter-hhs** [GSA/govt-urls#61]
howrightnow.com
nih.com
psoppc.com
thehearttruth.com
worklife4you.com
psoppc.info
ncats.io
hearttruth.net
namrs.net
oahpmdata.net
psoppc.net
thehearttruth.net
howrightnow.online
actagainstaids.org
ahrqadmin.org
ahrqdev.org
ahrqstg.org
brainattackcoalition.org
cdcpartners.org
cfsrportal.org
chainonline.org
coronaviruspreventionnetwork.org
ctsu.org
detroitself.org
gem-measures.org
genomereference.org
hearttruth.org
howrightnow.org
mepsdocs.org
nci-fyi.org
ncihub.org
nhlbiwgs.org
pccds-ln.org
pcorcds-ln.org
phs-nurse.org
presidentschallenge.org
psoppc.org
qualitynet.org
Quehacerahora.org
thecommunityguide.org
thehearttruth.org
uspreventiveservicestaskforce.org
vaccinefinder.org
scienceforum.sc

**Comment by h-m-f-t** [comment]
Thanks @shalllbetter-hhs!

**Comment by shalllbetter-hhs** [comment]
Two more:
ssbgportal.net
charmmtutorial.org

**Comment by dawnpm** [comment]
@shalllbetter-hhs thanks for all these! I've been working through the list, and have a few questions. For the following domains, could you let me know what they're used for? e.g., Website - open to public, Website - password protected, Email, API, Redirect, Unused, I don't know, Other

actagainstaids.org - Cert error
https://ahrqadmin.org/ - requires login
ahrqdev.org - internal use only?
ahrqstg.org - internal use only?
cdcpartners.org - no public use?

Other questions:

charmmtutorial.org redirects to https://www.charmm.org/wiki//index.php/CHARMM_Tutorial - is charmm.org in scope for the list? looks like yes.

gem-measures.org - I saw that this domain will be changing soon, will you let us know when the change has been completed, and what the new domain is?

More to come when we get through more of the list. Thanks.

**Comment by shalllbetter-hhs** [comment]
Your notes are generally correct.  I'm including domains I know are utilized by HHS for any reason.   There has been very little guidance re: M-22-09 on what non.-.gov to submit where, so I'm feeding the full list both to you and through our CSIRC for Cyber Hygiene.  This means you are getting a list that includes multiple options:

defensive redirects to .gov
defensive registrations w/o any addressing at all (cdcpartners.org)
misconfigured domains that have certificate errors (actagainstaids.org)
Management domains *intended* for internal use only (ahrqdev/ahrqstg/ahrgadmin)

chammer.org is in scope for sure.
For GEM, I don't l think the website is changing, just the meaning of the acronym (high-public sector science, that).

If you have specific guidance on what we should include where, that's great.  If you can sort them out and I can continue to add.  Great as well.

**Comment by dawnpm** [comment]
Thanks, @shalllbetter-hhs , we'll confer on how best to represent the purpose of your domains in our records. The uses for the list are evolving, and we appreciate your submissions!

**Comment by shalllbetter-hhs** [comment]
A full list and my assessment of why they exist.

actagainstaids.org | Defensive Registration
ahrqadmin.org | Internal   Sys Admin
ahrqdev.org | Internal   Dev
ahrqstg.org | Internal   Staging
brainattackcoalition.org | Open To   Public
cdcpartners.org | Redirect
cfsrportal.org | Redirect
chainonline.org | Redirect
charmm.org | Open To   Public
charmmtutorial.org | Open To   Public
citdbase.org | Open To   Public
coronaviruspreventionnetwork.org | Open To   Public
ctsu.org | Open To   Public
detroitself.org | Open To   Public
directihs.net | DIRECT   Protocol Anchor
docline.org | Defensive   Registration
everytry.org | Redirect
everytrycounts.org | Redirect
every-try-counts.org | Redirect
fatherhoodgov.info | Redirect
gem-beta.org | Redirect   / Beta UAC
gem-measures.org | Open To   Public
genbank.com | Defensive   Registration
genbank.net | Defensive   Registration
genbank.org | Defensive   Registration
genbank.xyz | Defensive   Registration
genomereference.org | Redirect
gratefulmed.com | Defensive   Registration
gratefulmed.info | Defensive   Registration
gratefulmed.net | Defensive   Registration
gratefulmed.org | Defensive   Registration
hapmap.org | Defensive   Registration
hcgov.us | Internal   Mail & Messaging
hearttruth.com | Redirect
hearttruth.net | Redirect
hearttruth.org | Redirect
howrightnow.com | Redirect
howrightnow.online | Redirect
howrightnow.org | Redirect
igm.org | Defensive   Registration
informationrx.info | Defensive   Registration
informationrx.net | Defensive   Registration
informationrx.org | Defensive   Registration
loansomedoc.net | Defensive   Registration
loansomedoc.org | Defensive   Registration
MedicalBillRights.com | Redirect
medicalbillrights.net | Redirect
medicalbillrights.org | Redirect
medlars.com | Defensive   Registration
medlars.info | Defensive   Registration
medlars.net | Defensive   Registration
medlars.org | Defensive   Registration
medlars.us | Defensive   Registration
medlineplus.com | Defensive   Registration
medlineplus.net | Defensive   Registration
medlineplus.org | Defensive   Registration
medlneplus.com | Defensive   Registration
medlneplus.info | Defensive   Registration
mepsdocs.org | Open To   Public
mepstech.com | Open To   Public
mesh.org | Defensive   Registration
namrs.net | Open To   Public
ncands.net | Open To   Public
ncats.io | Redirect
nci-fyi.org | Open To   Public
ncihub.org | Open To   Public
nhlbiwgs.org | Redirect
nih.com | Redirect
nihseniorhealth.biz | Defensive   Redirect
nihseniorhealth.com | Defensive   Redirect
nihseniorhealth.info | Defensive   Redirect
nihseniorhealth.net | Defensive   Redirect
nihseniorhealth.org | Defensive   Redirect
nlm.net | Defensive   Redirect
nlm.org | Defensive   Redirect
nlmgiftshop.com | Defensive   Redirect
nlmgiftshop.info | Defensive   Redirect
nlmgiftshop.net | Defensive   Redirect
oahpmdata.net | Open To   Public
pccds-ln.org | Open To   Public
pcorcds-ln.org | Redirect
phiresearchlab.org | Defensive   Registration
phs-nurse.org | Open To   Public
presidentschallenge.org | Redirect
psoppc.com | Rediret
psoppc.info | Rediret
psoppc.net | Rediret
psoppc.org | Open To   Public
pubchem.biz | Defensive   Registration
pubchem.info | Defensive   Registration
pubchem.us | Defensive   Registration
pubmed-central.com | Defensive Registration
pubmedcentral.info | Defensive Registration
pubmed-central.info | Defensive Registration
pubmed-central.net | Defensive Registration
pubmed-central.org | Defensive Registration
pubmedcentral.us | Defensive Registration
qualitynet.org | Redirect
Quehacerahora.org | Redirect
scienceforum.sc | Open To   Public
sisterstudy.org | Redirect
sitenv.org | Open To   Public
ssbgportal.net | Open To   Public
thecommunityguide.org | Open To   Public
thehearttruth.com | Redirect
thehearttruth.net | Redirect
thehearttruth.org | Redirect
thesisterstudy.org | Redirect
uspreventiveservicestaskforce.org | Open to the Public
vaccinefinder.org | Redirect
vetmed.wiki | Defensive Registration
vetmedinfo.net | Defensive Registration
vetmedinfo.org | Defensive Registration
worklife4you.com | Open To Public

**Comment by h-m-f-t** [comment]
Added in #78
