### ISSUE TITLE
CSOSA Domains Outside .Gov and .Mil

### ISSUE THREAD

**Issue by dawnpm** [GSA/govt-urls#64]
Ref: INC3760336

This email is to satisfy the reporting requirement of M 22-09 page 19 for CSOSA.

Attached is the list of domains that are owned by CSOSA that are not .gov or .mil.  All domains are parked and redirect to CSOSA.gov.

Let me know if there are any questions.
[non-gov-submission-template CSOSA.csv](https://github.com/GSA/govt-urls/files/8864725/non-gov-submission-template.CSOSA.csv)

Richard Wainwright | Chief Information Security Officer
Office of Information Technology, IT Security
Court Services and Offender Supervision Agency (CSOSA)

**Comment by h-m-f-t** [comment]
Got it.
