### ISSUE TITLE
CMS non .gov domains to add, cannot make PR

### ISSUE THREAD

**Issue by eschwein-usds** [GSA/govt-urls#67]
Hello!  I need to submit some non .gov domains for a federal agency, and tried making a PR, but got a permission denied message.

11:52:54.271: [govt-urls] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/cms-nondotgov:cms-nondotgov --set-upstream
remote: Permission to GSA/govt-urls.git denied to eschwein-usds.
fatal: unable to access 'https://github.com/GSA/govt-urls.git/': The requested URL returned error: 403

I suspect that I have to be a contributor to be able to make a PR?

I've attached a CSV file with the 10 domains we would like to report as a requirement of M-22-09
[cms-nondotgov-domains.csv](https://github.com/GSA/govt-urls/files/9031114/cms-nondotgov-domains.csv)

**Comment by h-m-f-t** [comment]
Thanks @eschwein-usds! WIP'ing your submission into a different format, and flagging my future self to compare https://www.hhs.gov/vulnerability-disclosure-policy/index.html with the larger HHS list.
Add/update/remove | Domain name | Agency | Maintaining office | Use case | Type of government | Federal branch | State | Comments
-- | -- | -- | -- | -- | -- | -- | -- | --
Add | ccwdata.org | Department of Health and Human Services | CMS |   | Federal | Executive | DC | The CMS Chronic Conditions Data Warehouse (CCW) provides researchers with   Medicare and Medicaid beneficiary, claims, and assessment data linked by   beneficiary across the continuum of care.
Add | csscoperations.com | Department of Health and Human Services | CMS |   | Federal | Executive | DC | The Customer Service and Support Center website provides information   about the Medicare Part C and Part D programs, as well as the   Medicare-Medicaid Financial Alignment Initiative (FAI).  Part of Centers for Medicare and Medicaid   Services.
Update | hcgov.us | Department of Health and Human Services | CMS |   | Federal | Executive | DC | Parked domain for Centers for Medicare and Medicaid Services.
Add | hfpp-ttp.org | Department of Health and Human Services | CMS |   | Federal | Executive | DC | Healthcare Fraud Prevention Partnership website at Centers for Medicare   and Medicaid Services"
Update | medicalbillrights.com | Department of Health and Human Services | CMS |   | Federal | Executive | DC |  
Update | medicalbillrights.net | Department of Health and Human Services | CMS |   | Federal | Executive | DC | Parked domain for Centers for Medicare and Medicaid Services.
Update | medicalbillrights.org | Department of Health and Human Services | CMS |   | Federal | Executive | DC | Parked domain for Centers for Medicare and Medicaid Services.
Add | pccqualitymonitoring.com | Department of Health and Human Services | CMS |   | Federal | Executive | DC | Communications Relational Assurance Database (CRAD) for the Provider   Customer Service Program System at Centers for Medicare and Medicaid   Services. https://crad.pccqualitymonitoring.com/#
Add | qualitynet.org | Department of Health and Human Services | CMS |   | Federal | Executive | DC | Redirects to qualittynet.cms.gov.    Established by the Centers for Medicare & Medicaid Services (CMS),   QualityNet provides healthcare quality improvement news, resources and data   reporting tools and applications used by healthcare providers and others.
Add | racwarehouse.org | Department of Health and Human Services | CMS |   | Federal | Executive | DC | CMS Recovery Audit Contractor Data Warehouse (RACDW) at Centers for   Medicare and Medicaid Services

**Comment by h-m-f-t** [comment]
With the exception of csscoperations.com and hcgov.us, none of the above domains are in the HHS VDP.

**Comment by h-m-f-t** [comment]
added in #78
