### ISSUE TITLE
add WorkwithUSAID.org

### ISSUE THREAD

**Issue by dawnpm** [GSA/govt-urls#71]
Announced via cx listserv 10/07/2022.

**Comment by h-m-f-t** [comment]
Domain redirects to a USAID-branded page and includes links to usaid.gov, sam.gov, grants.gov, and other gov-y services (GovDelivery). Using Google NS and hosted on Google Cloud; USAID [is a Google shop](https://www.usaid.gov/privacy-policy/systems-records-notices-sorns/usaid-30-google-apps-business-edition). Registered in 2020. 

(WorkWithUSAID.gov was registered about [~6 months ago](https://github.com/cisagov/dotgov-data/blame/main/current-full.csv#L6583), so they are probably planning to migrate this.)

LGTM.

**Comment by h-m-f-t** [comment]
Got it.
